name = "filespy"
version = "0.3.0"

description = "Get notified of filesystem events in Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "pta2002", repo = "gleam-filespy" }

[dependencies]
gleam_stdlib = "~> 0.31"
gleam_otp = "~> 0.7"
gleam_erlang = "~> 0.22"
fs = "~> 8.6"

[dev-dependencies]
gleeunit = "~> 0.10"
